# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0de0d661d910435d594fb6564292c881bd1ee3781c098c60b3065ed244f93e531813045097515bc5fe591a0bfec089fcca03962fac0a043ae08e8ec4e8692bd9
  s3_bucket: <%= ENV["S3_BUCKET"] %>
  s3_key_id: <%= ENV["S3_KEY_ID"] %>
  s3_secret_key: <%= ENV["S3_SECRET_KEY"] %>
  
test:
  secret_key_base: a583f97dea2d0176d255bed8bd08b214ef1f34d2ec6d0337753529657053e997ad9671028fa3bf954bb6e9a9f8ca3798b8ec49d099fb8a1c4a82feff57db1777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_bucket: <%= ENV["S3PROD_BUCKET"] %>
  s3_key_id: <%= ENV["S3_KEY_ID"] %>
  s3_secret_key: <%= ENV["S3_SECRET_KEY"] %>